export const en = {
    accountsetting: "Account settings",
    lockscreen: "Lock screen",
    signout: "Sign out",
    home: "Home",
    users: "Users",
    transaction: "Transaction",
    incoming: "Incoming",
    outgoing: "Outgoing",
    thisyeartransaction: "This Year Transaction",
    botransaction: "BO Transaction",
    transactionincoming: "Transaction Incoming",
    transactionoutgoing: "Transaction Outgoing",
    fotransaction: "FO Transaction",
    system: "System",
    listofrule: "List of Rules",
    fastschedulerconfiguration: "FAST scheduler configuration",
    banklist: "Bank list",
    fastbanklist: "FAST Bank list",
    usermanagement: "User management",
    userrole: "User role",
    userpolicy: "User policy",
    report: "Report",
    username: "Username",
    password: "Password",
    forgotpassword: "Forgot password?",
    "forgot-password": "Forgot password",
    signin: "Sign in",
    resetpassword: "Reset Password",
    norecordfound: "No record item found",
    action: "Action",
    from: "from",
    to: "to",
    results: "results",
    of: "of",
    showing: "Showing",
    changelanguagesuccess: "Change language successfully!",
    changesuccess: "Change success",
    "404page": "Sorry! The page you were looking for doesn't exist",
    gobacktohome: "Go back to Home Screen",
    nothaveperrmission: "Your not have permission to go to this page. Please login first!",
    "401Unauthorized": "Session expired or some information of this account have been changed. Please login again!",
    isRequired: "is required",
    minLength: "length must be greater or equal",
    maxLength: "length must be smaller or equal",
    isSame: "does not match with",
    isNotSame: "must be different with",
    successmessage: "Success Information",
    deletesuccess: "Delete success!!!",
    cannotdelete: "Can't delete.Please try again later",
    errormessage: "Error Information",
    getinformationsuccess: "Get information success!!!",
    saveinformationsuccess: "Save information success!!!",
    transactionsuccess: "Transaction success!!!",
    sessiontimeoutwarning: "Your are inactive. Your session will end in: ",
    keepsession: "Keep this session",
    close: "Close",
    sessiontimeout: "Session timeout",
    email: "Email",
    otpcode: "OTP Code",
    passwordsuccessreset: "Password have success reset and sent to your mail. Please check mail to get new password",
    changepassword: "Change password",
    clear: "Clear",
    confirmnewpass: "Confirm new password",
    newpassword: "New password",
    currentpassword: "Current password",
    address: "Address",
    birthday: "Birth Date",
    gender: "Gender",
    fullname: "Full name",
    information: "Information",
    selectroletoadduser: "Please select role to add this user",
    addusertorole: "Add user to role",
    inputtosearch: "Input to search",
    save: "Save",
    cancel: "Cancel",
    male: "Male",
    female: "Female",
    selectitem: "Please select items",
    emailregex: "not match format. Correct format must be: Abc@xyz.com",
    passwordupperregex: "not match format.Password must contain at least 1 uppercase character (A-Z)",
    passwordlowerregex: "not match format. Password must contain at least 1 lowercase character (a-z)",
    passworddigitregex: "not match format.Password must contain at least 1 number",
    usernameregex: "not match format.This field not allow input special character and space.",
};

export const vi = {
    accountsetting: "Cài đặt tài khoản",
    lockscreen: "Màn hình khóa",
    signout: "Đăng xuất",
    home: "Trang chủ",
    users: "Người dùng",
    transaction: "Giao dịch",
    incoming: "Giao dịch vào",
    outgoing: "Giao dịch ra",
    thisyeartransaction: "Giao dịch trong năm",
    botransaction: "Giao dịch BO",
    transactionincoming: "Quản lý Giao dịch nhận về",
    transactionoutgoing: "Quản lý giao dịch gửi đi",
    fotransaction: "Giao dịch FO",
    system: "Hệ thống",
    listofrule: "Quản lý quyền",
    fastschedulerconfiguration: "Quản lý lịch Fast-scheduler",
    banklist: "Quản lý ngân hàng",
    fastbanklist: "Quản lý FAST",
    usermanagement: "Quản lý người dùng",
    userrole: "Quản lý phân quyền",
    userpolicy: "Chính sách người dùng",
    report: "Báo cáo",
    username: "Tài khoản",
    password: "Mật khẩu",
    forgotpassword: "Quên mật khẩu?",
    "forgot-password": "Quên mật khẩu",
    signin: "Đăng nhập",
    resetpassword: "Lấy lại mật khẩu",
    action: "Hành động",
    norecordfound: "Không tìm thấy dữ liệu",
    from: "từ",
    to: "đến",
    results: "kết quả",
    of: "trên",
    showing: "Hiển thị",
    changelanguagesuccess: "Đổi ngôn ngữ thành công!",
    changesuccess: "Thay đổi ngôn ngữ",
    "404page": "Xin lỗi, trang bạn đang truy cập không tồn tại",
    gobacktohome: "Quay lại trang chủ",
    nothaveperrmission: "Bạn không có quyền để truy cập trang này. Hãy đăng nhập trước đã!",
    "401Unauthorized": "Phiên đăng nhập của bạn đã hết hạn hoặc tài khoản đã thay đổi thông tin. Vui lòng đăng nhập lại!",
    isRequired: "là trường bắt buộc",
    minLength: "phải có độ dài lớn hơn hoặc bằng",
    maxLength: "phải có độ dài nhỏ hơn hoặc bằng",
    isSame: "phải giống với",
    isNotSame: "phải khác",
    successmessage: "Thông báo thành công",
    deletesuccess: "Xóa thành công!",
    cannotdelete: "Không thể xóa. Vui lòng thử lại sau.",
    errormessage: "Thông báo thất bại",
    getinformationsuccess: "Lấy thông tin thành công!",
    saveinformationsuccess: "Lưu thông tin thành công!",
    sessiontimeoutwarning: "Bạn đã không hoạt động khá lâu. Phiên làm việc sẽ kết thúc sau: ",
    keepsession: "Giữ phiên làm việc này",
    close: "Đóng",
    sessiontimeout: "Phiên làm việc",
    email: "Hòm thư",
    otpcode: "Mã OTP",
    passwordsuccessreset: "Mật khẩu đã được khởi tạo lại thành công. Hãy kiểm tra mail để lấy mật khẩu mới",
    changepassword: "Thay đổi mật khẩu",
    clear: "Làm mới",
    confirmnewpass: "Nhập lại mật khẩu",
    newpassword: "Mật khẩu mới",
    currentpassword: "Mật khẩu hiện tại",
    address: "Đia chỉ",
    birthday: "Ngày sinh nhật",
    gender: "Giới tính",
    fullname: "Tên đầy đủ",
    information: "Thông tin",
    selectroletoadduser: "Xin hãy chọn quyền cho tài khoản của bạn trước",
    addusertorole: "Thêm tài khoản vào role",
    inputtosearch: "Nhập dữ liệu để tìm kiếm",
    save: "Lưu",
    cancel: "Hủy bỏ",
    male: "Nam",
    female: "Nữ",
    selectitem: "Xin hãy chọn dữ liệu",
    emailregex: "không đúng định dạng. Định dạng mail chuẩn có dạng: Abc@xyz.com",
    passwordupperregex: "không đúng định dạng.Mật khẩu cần chứa ít nhất 1 chữ cái viết hoa (A-Z)",
    passwordlowerregex: "không đúng định dạng.Mật khẩu cần chứa ít nhất 1 chữ cái viết thường (a-z)",
    passworddigitregex: "không đúng định dạng.Mật khẩu cần chứa ít nhất 1 con số (0-9)",
    usernameregex: "Không đúng định dạng. Trường này không cho phép dấu cách và các kí tự đặc biệt",
};

